
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '629EBEA9F25293B30498AD4163EB9775'
    
_lr_action_items = {'$end':([1,4,5,6,7,8,9,10,11,12,13,20,24,25,26,29,35,],[-3,-12,0,-13,-5,-8,-10,-2,-11,-1,-12,-9,-6,-7,-4,-15,-14,]),'BODY':([32,],[35,]),'RPAREN':([6,7,8,9,11,13,14,20,22,23,25,26,27,28,29,33,34,],[-13,-5,-8,-10,-11,-12,20,-9,29,-17,-7,-4,-19,32,-15,-16,-18,]),'INT':([0,2,16,17,18,19,30,],[11,11,11,11,11,11,11,]),'ID':([0,2,3,16,17,18,19,21,30,31,],[4,13,15,13,13,13,13,27,13,27,]),'MULT_OP':([4,6,7,8,9,11,13,20,25,26,29,],[-12,-13,18,-8,-10,-11,-12,-9,-7,18,-15,]),'EQ':([4,],[17,]),'FUNCTION':([0,],[3,]),'FLOAT':([0,2,16,17,18,19,30,],[9,9,9,9,9,9,9,]),'LPAREN':([0,2,4,13,15,16,17,18,19,30,],[2,2,16,16,21,2,2,2,2,2,]),'COMMA':([6,7,8,9,11,13,20,23,25,26,27,29,],[-13,-5,-8,-10,-11,-12,-9,30,-7,-4,31,-15,]),'ADD_OP':([4,6,7,8,9,11,12,13,14,20,23,24,25,26,29,],[-12,-13,-5,-8,-10,-11,19,-12,19,-9,19,19,-7,-4,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,2,16,17,19,30,],[7,7,7,7,26,7,]),'factor':([0,2,16,17,18,19,30,],[8,8,8,8,25,8,8,]),'function_def':([0,],[1,]),'paramlist':([21,31,],[28,34,]),'assignment':([0,],[10,]),'command':([0,],[5,]),'exprlist':([16,30,],[22,33,]),'arith_expr':([0,2,16,17,30,],[12,14,23,24,23,]),'function_call':([0,2,16,17,18,19,30,],[6,6,6,6,6,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> arith_expr','command',1,'p_command','pluto3.py',74),
  ('command -> assignment','command',1,'p_command','pluto3.py',75),
  ('command -> function_def','command',1,'p_command','pluto3.py',76),
  ('arith_expr -> arith_expr ADD_OP term','arith_expr',3,'p_arith_expr','pluto3.py',81),
  ('arith_expr -> term','arith_expr',1,'p_arith_expr_term','pluto3.py',89),
  ('assignment -> ID EQ arith_expr','assignment',3,'p_assignment','pluto3.py',94),
  ('term -> term MULT_OP factor','term',3,'p_term','pluto3.py',103),
  ('term -> factor','term',1,'p_term_factor','pluto3.py',111),
  ('factor -> LPAREN arith_expr RPAREN','factor',3,'p_factor','pluto3.py',116),
  ('factor -> FLOAT','factor',1,'p_factor_numeric','pluto3.py',121),
  ('factor -> INT','factor',1,'p_factor_numeric','pluto3.py',122),
  ('factor -> ID','factor',1,'p_factor_var','pluto3.py',127),
  ('factor -> function_call','factor',1,'p_factor_function_call','pluto3.py',136),
  ('function_def -> FUNCTION ID LPAREN paramlist RPAREN BODY','function_def',6,'p_function_def','pluto3.py',141),
  ('function_call -> ID LPAREN exprlist RPAREN','function_call',4,'p_function_call','pluto3.py',151),
  ('exprlist -> arith_expr COMMA exprlist','exprlist',3,'p_exprlist','pluto3.py',158),
  ('exprlist -> arith_expr','exprlist',1,'p_exprlist_expr','pluto3.py',163),
  ('paramlist -> ID COMMA paramlist','paramlist',3,'p_paramlist','pluto3.py',168),
  ('paramlist -> ID','paramlist',1,'p_paramlist_single','pluto3.py',173),
]
